# Generated by Django 4.0.3 on 2022-03-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_remove_like_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='likes',
        ),
        migrations.AddField(
            model_name='pin',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
