# Generated by Django 4.0.3 on 2022-03-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_remove_pin_likes_pin_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='liked',
        ),
        migrations.AddField(
            model_name='pin',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='pins', to='pins.like'),
        ),
    ]
