# Generated by Django 4.0.3 on 2022-03-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_like_pin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='label',
            new_name='title',
        ),
    ]
