# Generated by Django 4.0.3 on 2022-03-29 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0005_alter_pin_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='username',
        ),
    ]
