# Generated by Django 4.0.3 on 2022-05-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmodel_remove_thread_first_remove_thread_second_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='receiver',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
