# Generated by Django 4.0.3 on 2022-05-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmodel_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='receiver',
        ),
    ]
